# Generated by Django 6.0.7 on 2026-07-21 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_delete_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, help_text="Déjalo vacío si esta es una categoría principal (ej. 'Cuidado del cabello')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria'),
        ),
    ]
