# Generated by Django 6.0.7 on 2026-07-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_categoria_options_categoria_categoria_padre'),
        ('inventario', '0003_crear_categoria_nueva_coleccion'),
    ]

    operations = [
    ]
