# Generated by Django 6.0.7 on 2026-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1_titulo', models.CharField(default='El clóset de belleza que sí quieren tener', max_length=100)),
                ('slide1_texto', models.TextField(default='Cosmetiqueras, accesorios y maquillaje de tus personajes favoritos, pensados para manos pequeñas.')),
                ('slide1_color_a', models.CharField(default='#6C3B8C', max_length=7)),
                ('slide1_color_b', models.CharField(default='#2D1B4E', max_length=7)),
                ('slide2_titulo', models.CharField(default='Hasta 20% menos en set seleccionados', max_length=100)),
                ('slide2_texto', models.TextField(default='Aprovecha antes de que se agoten las referencias más buscadas del mes.')),
                ('slide2_color_a', models.CharField(default='#8E44AD', max_length=7)),
                ('slide2_color_b', models.CharField(default='#4A1F6A', max_length=7)),
                ('slide3_titulo', models.CharField(default='Nueva colección Toy Story ya está aquí', max_length=100)),
                ('slide3_texto', models.TextField(default='Sombras, brillos y accesorios de cabello para armar looks llenos de imaginación.')),
                ('slide3_color_a', models.CharField(default='#9B59B6', max_length=7)),
                ('slide3_color_b', models.CharField(default='#2D1B4E', max_length=7)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diseño del sitio',
                'verbose_name_plural': 'Diseño del sitio',
            },
        ),
    ]
