# Generated by Django 6.0.7 on 2026-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenositio',
            name='slide1_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/'),
        ),
        migrations.AddField(
            model_name='disenositio',
            name='slide2_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/'),
        ),
        migrations.AddField(
            model_name='disenositio',
            name='slide3_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/'),
        ),
    ]
