# Generated by Django 6.0.7 on 2026-07-21 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_actual', models.CharField(choices=[('preparando', 'Preparando pedido'), ('en_camino', 'En camino'), ('en_reparto', 'En reparto local'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='preparando', max_length=20)),
                ('numero_guia', models.CharField(max_length=20, unique=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_destinatario', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('metodo_pago', models.CharField(blank=True, choices=[('nequi', 'Nequi'), ('tarjeta', 'Tarjeta (Visa/Mastercard)'), ('pse', 'PSE'), ('mercadopago', 'Mercado Pago'), ('contraentrega', 'Pago contraentrega')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('preparando', 'Preparando pedido'), ('en_camino', 'En camino'), ('en_reparto', 'En reparto local'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rastreo.envio')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
