# Generated by Django 6.0.7 on 2026-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado_actual',
            field=models.CharField(choices=[('preparando', 'En preparación'), ('listo', 'Listo'), ('en_camino', 'En viaje'), ('entregado', 'Llegó a su destino'), ('cancelado', 'Cancelado')], default='preparando', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.CharField(choices=[('preparando', 'En preparación'), ('listo', 'Listo'), ('en_camino', 'En viaje'), ('entregado', 'Llegó a su destino'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
