# Generated by Django 6.0.7 on 2026-07-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='envio',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='envio',
            name='nombre_destinatario',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='envio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
