# Generated by Django 6.0.7 on 2026-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0002_envio_ciudad_envio_correo_envio_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('nequi', 'Nequi'), ('tarjeta', 'Tarjeta (Visa/Mastercard)'), ('pse', 'PSE'), ('mercadopago', 'Mercado Pago'), ('contraentrega', 'Pago contraentrega')], max_length=20),
        ),
    ]
