# Generated by Django 6.0.7 on 2026-07-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0003_envio_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='envio',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
