# Generated by Django 6.0.7 on 2026-07-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0002_alter_envio_estado_actual_and_more'),
        ('rastreo', '0004_envio_cantidad_envio_precio_unitario'),
    ]

    operations = [
    ]
