# Generated by Django 6.0.7 on 2026-07-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0005_merge_20260727_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Empresa de Envíos',
                'verbose_name_plural': 'Empresas de Envíos',
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='empresa_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='rastreo.empresaenvio'),
        ),
    ]
