# Generated by Django 6.0.7 on 2026-07-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreo', '0006_empresaenvio_envio_empresa_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_asignacion_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
