# Generated by Django 6.0.7 on 2026-07-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
